name: Build and Deploy Docs

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Sphinx HTML docs
        working-directory: docs
        run: |
          export SECRET_KEY=dummy
          export DEBUG=False
          export ALLOWED_HOSTS=localhost
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
