name: Docker CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t server-test .

    - name: Run Docker container
      run:  docker run -d --name server-test -p 8000:8000  server-test

    - name: Wait for containers to initialize
      run: sleep 10

    - name: Stop container
      if: always()
      run: docker stop server-test

    - name: Remove container
      if: always()
      run: docker rm server-test