name: Docker CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t server-test .

    - name: Run Docker container
      run:  docker run -d --name server-test -p 8000:8000  server-test

    - name: Wait for containers to initialize
      run: sleep 10

    - name: Check if server is responding
      run: |
        for i in {1..10}; do
          echo "Attempt $i: Checking http://localhost:8000"
          if curl --fail http://localhost:8000; then
            echo "Server is responding!"
            exit 0
          fi
          echo "Server not responding yet. Waiting 15 seconds..."
          sleep 15
        done

        echo "Server did not respond after 10 attempts. Showing logs:"
        docker logs server-test
        exit 1

    - name: Stop container
      if: always()
      run: docker stop server-test

    - name: Remove container
      if: always()
      run: docker rm server-test